---

- name: Configure an ACL
  gather_facts: no
  hosts: pynet-rtr1
  vars:
    creds:
        host: "{{ host }}"
        username: "{{ username }}"
        password: "{{ password }}"
  tasks:
    - name: Configure logging
      ios_config:
        provider: "{{ creds }}"
        lines: 
          - logging buffered 10000
          - no logging console
        match: line
      tags: logging

    - name: Configure ACL
      ios_config:
        provider: "{{ creds }}"
        lines: 
          - permit ip host 1.1.1.1 any log
          - permit ip host 2.2.2.2 any log
          - permit ip host 3.3.3.3 any log
          - permit ip host 4.4.4.4 any log
          - permit ip host 5.5.5.5 any log
        parents: ["ip access-list extended TEST-ACL"]
        before: ["no ip access-list extended TEST-ACL"]
        replace: block
        match: line
      tags: ACL
      notify: 
        - write mem

  handlers:
    - name: write mem
      ios_command:
        commands: "write mem"
        provider: "{{ creds }}"
      changed_when: True
